version: 0.0
resources:
  - ecs:
      - my-ecs-cluster-name:
          service: my-ecs-service-name
          taskDefinition: ECS_TASK_DEFINITION

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 3600
      runas: root
