version: 0.0
resources:
  - ecs:
      - my-cluster:
          service: ecs-service
          taskDefinition: ecs-task

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 3600
      runas: root
