version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "965080479351"
    AWS_REGION: "ap-southeast-1"
    IMAGE_REPO_NAME: "nodejs-hello"
    ECR_REGISTRY: "965080479351.dkr.ecr.ap-southeast-1.amazonaws.com"


phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - echo Tagging Docker image...
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"app-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

  post_build:
    commands:
      - echo Uploading imagedefinitions.json to S3...
      - aws s3 cp imagedefinitions.json s3://nodejs-helloworld/imagedefinitions.json  
      - echo Build complete. Imagedefinitions file uploaded to S3.

artifacts:
  files:
    - imagedefinitions.json
